Add container file

diff --git a/16/bookworm-no-initdb-if-exist/Containerfile b/16/bookworm-no-initdb-if-exist/Containerfile
--- a/16/bookworm-no-initdb-if-exist/Containerfile
+++ b/16/bookworm-no-initdb-if-exist/Containerfile
@@ -1,6 +1,9 @@
 FROM postgres:16
 
-COPY docker-ensure-no-initdb-if-exist.sh /usr/local/bin/docker-ensure-initdb.sh
-RUN rm -f /usr/local/bin/docker-enforce-initdb.sh && ln -sT docker-ensure-initdb.sh /usr/local/bin/docker-enforce-initdb.sh
+# Set working directory
+WORKDIR /var/lib/postgresql/data
 
-ENTRYPOINT ["docker-entrypoint.sh"]
+# Check if the database directory exists (indicates existing data)
+RUN [ ! -d "$PGDATA" ] && echo "Database directory not found, initializing..." || echo "Database directory found, skipping initialization."
+
+#ENTRYPOINT ["docker-entrypoint.sh"]
